# Introduction to Tensorflow Fundamentals

TensorFlow is a deep-learning framework that offers a straight-forward and intuitive way to build powerful models used to solve complex problems. The purpose of this notebook is to dig into some of the fundamentals behind how TensorFlow works.

* https://www.tensorflow.org/learn
* https://www.tensorflow.org/api_docs/python/tf

## Imports

In [1]:
import tensorflow as tf
import numpy as np

## Creating Tensors

A tensor is a container which can house data in N dimensions. Often and erroneously used interchangeably with the matrix (which is specifically a 2-dimensional tensor), tensors are generalizations of matrices to N-dimensional space.

* https://www.kdnuggets.com/2018/05/wtf-tensor.html
* https://www.tensorflow.org/api_docs/python/tf/Tensor

TensorFlow offers many ways to create Tensors.

* `tf.constant` - Creates a constant Tensor (can NOT change)
* `tf.Variable` - Creates a variable Tensor (can change)
* `tf.random.normal` - Creates a random Tensor using normal distributions
* `tf.ones` - Creates a Tensor of all ones
* `tf.zeros` - Creates a Tensor of all zeros

### Tensors with tf.constant (Used when Tensors Can NOT Change)

In [2]:
# Scalar Tensor
scalar = tf.constant(7.0)
scalar

2023-09-12 18:24:33.557894: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2023-09-12 18:24:33.557908: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2023-09-12 18:24:33.557912: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2023-09-12 18:24:33.557938: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-12 18:24:33.557950: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [3]:
# Checking Scalar Dims
scalar.ndim

0

In [4]:
# Vector Tensor
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Checking Vector Dims
vector.ndim

1

In [6]:
# Matrix Tensor (more than one dim)
matrix = tf.constant([[27, 83],
                      [10, 19]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 83],
       [10, 19]], dtype=int32)>

In [7]:
# Checking Matrix Dims
matrix.ndim

2

In [8]:
# N Dim Tensor
tensor = tf.constant([[[27, 83], [10, 19]],
                      [[1,   2], [3,   4]],
                      [[4,   5], [6,   7]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[27, 83],
        [10, 19]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 4,  5],
        [ 6,  7]]], dtype=int32)>

In [9]:
# Dim of Tensor
tensor.ndim

3

In [10]:
# Matrix dtype specify as float16 (default without specifying is float32)
matrix_float_16 = tf.constant([[27.0, 83.0],
                      [19.0, 10.0]], dtype=tf.float16)
matrix_float_16

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[27., 83.],
       [19., 10.]], dtype=float16)>

### Tensors with tf.Variable (Used when Tensors Can Change)

In [11]:
variable_tensor = tf.Variable([27, 83])
constant_tensor = tf.constant([27, 83])

variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([27, 83], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([27, 83], dtype=int32)>)

In [12]:
# Testing what happens when attempting to change variable tensors
# NOTE: Attempting to change constant tensors raise errors
variable_tensor[0].assign(19)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19, 83], dtype=int32)>

### Tensors with tf.random

In [13]:
# Generating a random tensor from a specific seed to ensure the same tensor is created
random_tensor_generator = tf.random.Generator.from_seed(83)
random_tensor = random_tensor_generator.normal(shape=(3, 2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.49539253, -0.7584407 ],
       [ 0.13736528, -0.4419888 ],
       [-0.6564125 , -2.2867968 ]], dtype=float32)>

### Shuffle Tensor Values with tf.random.shuffle

In [14]:
not_shuffled = tf.constant([[27, 83],
                            [10, 19],
                            [15, 16]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27, 83],
       [10, 19],
       [15, 16]], dtype=int32)>

In [15]:
# Dealing with Random seeds
# Setting global level seet
tf.random.set_seed(10)
not_shuffled = tf.constant([[27, 83],
                            [10, 19],
                            [15, 16]])
tf.random.shuffle(not_shuffled), tf.random.shuffle(not_shuffled)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[27, 83],
        [15, 16],
        [10, 19]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[15, 16],
        [27, 83],
        [10, 19]], dtype=int32)>)

### Tensor with Ones and Zeros
The main difference between NumPy arrays and TensorFlow arrays is Tensors can run on GPU

In [16]:
# Create tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
# Create tensor of zeros
tf.zeros([5, 6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
# Tensor from numpy
numpy_array = np.arange(1, 25) # 24 total items

# Taking vector of [1, 2, 3, ... 24, 25] and turning into Tensor of shape [2, 3, 4]
# NOTE: Shape has to be multiple of total elements
A = tf.constant(numpy_array, shape=[2,3,4])
B = tf.constant(numpy_array)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

## Getting Information from Tensors
- Shape: The shape of the dimension
- Rank: The dimension of the tensor
- Axis or Dimension: Accesssing a particular dimension of a tensor
- Size: Total elements in tensor

In [19]:
# Sample rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
# Getting information from tensor
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor), rank_4_tensor.dtype

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32)

### Indexing Tensors
Tensors can by indexed just like python lists

In [21]:
# Get first 2 elements for each index
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
# Get the first each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]  # NOTE: rank_4_tensor[:1, :1, :1, :]  != rank_4_tensor[0, 0, 0, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Reshape Tensors

In [23]:
rank_2_tensor = tf.constant([[27, 83],
                             [10, 19]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 83],
       [10, 19]], dtype=int32)>

In [24]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([83, 19], dtype=int32)>

In [25]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[27],
        [83]],

       [[10],
        [19]]], dtype=int32)>

In [26]:
# Add in extra dimension to our rank 2 tensor (alternative way)
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[27],
        [83]],

       [[10],
        [19]]], dtype=int32)>

## Manipulating Tensors (Tensor Operations)
Standard Operators:
`+`, `-`, `*`, `/`, `@`

TensorFlow offers a standard way to multiply matrices. When a constant is multiplied by a Tensor using `*`, it acts as scalar multiplication or piece wise multiplication. Alternatively, matrix multiplication is used through the `@` symbol.

In addition to standard operators, TensorFlow offers standard functions that offer alternative ways to perform operations.

### Standard Operators

TensorFlow offers standard operators when working with Tensors.

Operators: `+`, `-`, `*`, `/`

In [27]:
# Basic Opertions with a scalar
tensor = tf.constant([[27, 83],
                      [10, 19]])

tensor + 1, tensor - 1, tensor * 2, tensor / 2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[28, 84],
        [11, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[26, 82],
        [ 9, 18]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 54, 166],
        [ 20,  38]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[13.5, 41.5],
        [ 5. ,  9.5]])>)

In [28]:
# Adding/Subtracting two tensors
tensor_A = tf.constant([[27, 83],
                       [10, 19]])
tensor_B = tf.constant([[13, 17],
                        [10, 1]])
tensor_A + tensor_B, tensor_A - tensor_B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 40, 100],
        [ 20,  20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[14, 66],
        [ 0, 18]], dtype=int32)>)

In [29]:
# Multiplying/Diving Tensors (Element Wise)
tensor_A = tf.constant([[27, 83],
                       [10, 19]])
tensor_B = tf.constant([[13, 17],
                        [10, 1]])
tensor_A * tensor_B, tensor_A / tensor_B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 351, 1411],
        [ 100,   19]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[ 2.07692308,  4.88235294],
        [ 1.        , 19.        ]])>)

### Tensor Multiplication

Tensor multiplication results in the two following rules:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [30]:
# Matrix Multiplication (NOT Element Wise) Using tf.linalg.matmul (can shorten to tf.matmul)
tensor_A = tf.constant([[27, 83],
                        [10, 19]])
tensor_B = tf.constant([[13, 17],
                        [10, 1]])
tf.matmul(tensor_A, tensor_B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1181,  542],
       [ 320,  189]], dtype=int32)>

In [31]:
# Matrix Multiplication (NOT Element Wise) Using `@` Operator
tensor_A = tf.constant([[27, 83],
                        [10, 19]])
tensor_B = tf.constant([[13, 17],
                        [10, 1]])
tensor_A @ tensor_B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1181,  542],
       [ 320,  189]], dtype=int32)>

In [32]:
# Transposing Matrices
tensor = tf.constant([[27, 83],
                      [10, 19],
                      [13, 17]])
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[27, 10, 13],
       [83, 19, 17]], dtype=int32)>

### Matrix Dot Products
Matrix Multiplication is also referred to as the dot product.

Using Matrix Multiplication:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [33]:
# Dotproduct Matrices (Same as multiplication)
tensor_A = tf.constant([[27, 83],
                        [10, 19]])
tensor_B = tf.constant([[13, 17],
                        [10, 1]])

tf.tensordot(tensor_A, tensor_B, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1181,  542],
       [ 320,  189]], dtype=int32)>

In [34]:
# Transpose Vs Reshape
tensor_A = tf.constant([[27, 83],
                        [10, 19],
                        [13, 17]])
tf.transpose(tensor_A), tf.reshape(tensor_A, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[27, 10, 13],
        [83, 19, 17]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[27, 83, 10],
        [19, 13, 17]], dtype=int32)>)

### Changing Datatype of Tensor

Tensors are structured with a standard datatype across all elements in the Tensor. Tensorflow has standard datatypes:

* `tf.int16`, `tf.int32`, `tf.int64`
* `tf.float16`, `tf.float32`, `tf.float64`
* `tf.bool`

See the complete list in the link below.

* https://www.tensorflow.org/api_docs/python/tf/dtypes

These values can be casted as a new datatype using `tf.cast`.

In [35]:
A = tf.constant([1.2, 3.4])
B = tf.constant([3, 4])

A.dtype, B.dtype

(tf.float32, tf.int32)

In [36]:
# Casting A and B to lower precisions

tf.cast(A, tf.float16), tf.cast(B, tf.int16)

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([3, 4], dtype=int16)>)

In [37]:
# Casting float to int and Vice versa
# NOTE: Cast from float to into will lose precision so use sparingly!
tf.cast(A, tf.int32), tf.cast(B, tf.float32)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>)

## Aggregating Tensors
The purpose of aggregation is to combine data into a lower represented dimension. This includes operations such as:

* absolute value
* min
* max
* mean
* sum
* standard deviation
* variance
* squeeze

### Absolute Values

In [38]:
# Absolute Values of Tensor
A = tf.constant([-3, 4, 1, -2])
tf.abs(A)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 1, 2], dtype=int32)>

### Basic Aggregations
Getting the min, max, mean, sum, etc.

In [39]:
# Create a random tensor with values between 0 and 100 of size 50
A = tf.constant(np.random.randint(0, 100, size=50))
A, tf.size(A), A.shape, A.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([75, 43,  8, 63, 21, 41,  7, 48, 21, 66, 19, 19, 99, 92, 70, 93, 19,
        87, 14, 69, 92, 25, 39, 61, 61, 81, 96, 63, 25, 78, 67, 36, 92, 99,
         7, 17, 94, 69, 18, 21, 37, 40, 60,  3, 65, 48, 78, 72, 37, 11])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [40]:
# Minimum of Tensor
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [41]:
# Maximum of Tensor
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [42]:
# Mean of Tensor
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [43]:
# Sum of Tensor
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2566>

In [44]:
# Standard Deviation of Tensor
tf.math.reduce_std(tf.cast(A, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.542133>

In [45]:
# Variance of Tensor
tf.math.reduce_variance(tf.cast(A, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=872.7376>

In [46]:
# Finding position of Mins in a Tensor
A = tf.random.uniform(shape=[50])

tf.argmin(A), A[tf.argmin(A)] == tf.reduce_min(A), tf.reduce_min(A)

(<tf.Tensor: shape=(), dtype=int64, numpy=28>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.010968566>)

In [47]:
# Finding position of Max in a Tensor
A = tf.random.uniform(shape=[50])

tf.argmax(A), A[tf.argmax(A)] == tf.reduce_max(A), tf.reduce_max(A)

(<tf.Tensor: shape=(), dtype=int64, numpy=8>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9526142>)

### Squeezing a Tensor
Removing all 1 Dimensional Axes

In [48]:
A = tf.constant(tf.random.uniform(shape=[1, 1, 1, 1, 50]))
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.21397555, 0.2643757 , 0.28710473, 0.25718975, 0.52617586,
           0.91361344, 0.0447216 , 0.10029984, 0.09849989, 0.86648834,
           0.24473143, 0.56366694, 0.03929579, 0.12343621, 0.19966185,
           0.1920501 , 0.28218448, 0.15347826, 0.53748095, 0.27362394,
           0.2531482 , 0.36486518, 0.21162462, 0.62031853, 0.5597439 ,
           0.9813552 , 0.19455218, 0.19763148, 0.1973288 , 0.03005874,
           0.10550642, 0.47597027, 0.28553474, 0.08011901, 0.5166364 ,
           0.3910675 , 0.4203813 , 0.3037548 , 0.07092381, 0.45484078,
           0.45768797, 0.29157996, 0.3182882 , 0.30745256, 0.25168908,
           0.540053  , 0.67481935, 0.9355844 , 0.92940557, 0.2120583 ]]]]],
      dtype=float32)>

In [49]:
A_squeezed = tf.squeeze(A)
A_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.21397555, 0.2643757 , 0.28710473, 0.25718975, 0.52617586,
       0.91361344, 0.0447216 , 0.10029984, 0.09849989, 0.86648834,
       0.24473143, 0.56366694, 0.03929579, 0.12343621, 0.19966185,
       0.1920501 , 0.28218448, 0.15347826, 0.53748095, 0.27362394,
       0.2531482 , 0.36486518, 0.21162462, 0.62031853, 0.5597439 ,
       0.9813552 , 0.19455218, 0.19763148, 0.1973288 , 0.03005874,
       0.10550642, 0.47597027, 0.28553474, 0.08011901, 0.5166364 ,
       0.3910675 , 0.4203813 , 0.3037548 , 0.07092381, 0.45484078,
       0.45768797, 0.29157996, 0.3182882 , 0.30745256, 0.25168908,
       0.540053  , 0.67481935, 0.9355844 , 0.92940557, 0.2120583 ],
      dtype=float32)>

## One Hot Encoding Tensors

The purpose of a one hot encoder is to transform text data into a numerical representation, allowing mathematical operations to be performed.

For instance, a one hot encoded representation of text:

* Encoding repeated strings to an int ('red', 'green', 'blue') -> (1, 0, 0)

In [50]:
some_list = [0, 1, 2, 3, 0, 2, 1, 1] # Could be red, green, blue, purple
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

## Checking Devices Available (CPU, GPU, TPU)
NOTE: TensorFlow will automatically use a CUDA GPU if one is available

In [51]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]