# TensorFlow Developer Exam Overview


## Notebook Details

This section goes over the Table of Contents for this notebook, along with listing out the resources referenced in this notebook.

### Table of Contents

The various sections and links to those section in this notebook.

#### 1. Guide to TensorFlow & Modeling

1. TensorFlow Inputs & Outputs Table
2. Overfitting

#### 2. TensorFlow Certificate Candidate Handbook

1. TensorFlow Development Skills
    - 1.1. Know how to program in Python, resolve Python issues, and compile and run Python programs in PyCharm.
    - 1.2. Know how to find information about TensorFlow APIs, including how to find guides and API references on tensorflow.org.
    - 1.3. Know how to debug, investigate, and solve error messages from the TensorFlow API.
    - 1.4. Know how to search beyond tensorflow.org, as and when necessary, to solve your TensorFlow questions.
    - 1.5. Know how to create ML models using TensorFlow where the model size is reasonable for the problem being solved.
    - 1.6. Know how to save ML models and check the model file size.
    - 1.7. Understand the compatibility discrepancies between different versions of TensorFlow.
2. Building and training neural network models using TensorFlow 2.x
    - 2.1. Use TensorFlow 2.x.
    - 2.2. Build, compile and train machine learning (ML) models using TensorFlow.
    - 2.3. Preprocess data to get it ready for use in a model.
    - 2.4. Use models to predict results.
    - 2.5. Build sequential models with multiple layers.
    - 2.6. Build and train models for binary classification.
    - 2.7. Build and train models for multi-class categorization.
    - 2.8. Plot loss and accuracy of a trained model.
    - 2.9. Identify strategies to prevent overfitting, including augmentation and dropout.
    - 2.10. Use pretrained models (transfer learning).
    - 2.11. Extract features from pre-trained models.
    - 2.12. Ensure that inputs to a model are in the correct shape.
    - 2.13. Ensure that you can match test data to the input shape of a neural network.
    - 2.14. Ensure you can match output data of a neural network to specified input shape for test data.
    - 2.15. Understand batch loading of data.
    - 2.16. Use callbacks to trigger the end of training cycles.
    - 2.17. Use datasets from different sources.
    - 2.18. Use datasets in different formats, including json and csv.
    - 2.19. Use datasets from tf.data.datasets.
3. Image Classification
    - 3.1. Define Convolutional neural networks with Conv2D and pooling layers.
    - 3.2. Build and train models to process real-world image datasets.
    - 3.3. Understand how to use convolutions to improve your neural network.
    - 3.4. Use real-world images in different shapes and sizes.
    - 3.5. Use image augmentation to prevent overfitting.
    - 3.6. Use ImageDataGenerator.
    - 3.7. Understand how ImageDataGenerator labels images based on the directory structure.
4. Natural language processing (NLP)
    - 4.1. Build natural language processing systems using TensorFlow.
    - 4.2. Prepare text to use in TensorFlow models.
    - 4.3. Build models that identify the category of a piece of text using binary categorization
    - 4.4. Build models that identify the category of a piece of text using multi-class categorization
    - 4.5. Use word embeddings in your TensorFlow model.
    - 4.6. Use LSTMs in your model to classify text for either binary or multi-class categorization.
    - 4.7. Add RNN and GRU layers to your model.
    - 4.8. Use RNNS, LSTMs, GRUs and CNNs in models that work with text.
    - 4.9. Train LSTMs on existing text to generate text (such as songs and poetry)
5. Time series, sequences and predictions
    - 5.1. Train, tune and use time series, sequence and prediction models.
    - 5.2. Train models to predict values for both univariate and multivariate time series.
    - 5.3. Prepare data for time series learning.
    - 5.4. Understand Mean Absolute Error (MAE) and how it can be used to evaluate accuracy of sequence models.
    - 5.5. Use RNNs and CNNs for time series, sequence and forecasting models.
    - 5.6. Identify when to use trailing versus centred windows.
    - 5.7. Use TensorFlow for forecasting.
    - 5.8. Prepare features and labels.
    - 5.9. Identify and compensate for sequence bias.
    - 5.10. Adjust the learning rate dynamically in time series, sequence and prediction models.

### Resources

The various resources/articles used to create this notebook, along with various resources/articles that are very useful.

1. [Article by Judy Traj](https://medium.com/@judytraj007/getting-the-google-tensorflow-developer-certification-51cf1e4c2bf9)
2. [Article by R. Barbero](https://medium.com/@rbarbero/tensorflow-certification-tips-d1e0385668c8)
3. [Github Repo of Tensorflow-Certificate Study Guide](https://github.com/kolasniwash/tensorflow-certification-study-guide)
4. [TensorFlow: Guide to Getting Started](https://www.kaggle.com/code/nicholasjhana/tensorflow-guide-to-getting-started/notebook)
5. [LinkedIn Article by Vivek Bomabtkar](https://www.linkedin.com/pulse/tensorflow-developer-certification-vivek-bombatkar/)
6. [LLM Notebook in TensorFlow by FOUCARDM on Kaggle](https://www.kaggle.com/code/foucardm/tensorflow-certification-guide-text-data/notebook)
7. [Bidirectional RNN Architecture](https://www.geeksforgeeks.org/bidirectional-lstm-in-nlp/)
8. [LSTM Architecture](https://www.geeksforgeeks.org/deep-learning-introduction-to-long-short-term-memory/)
9. [GRU Architecture](https://towardsdatascience.com/understanding-gru-networks-2ef37df6c9be)
10. [Metrics in Timeseries Forecasting](https://mlpills.dev/time-series/error-metrics-for-time-series-forecasting/)
11. [Univariate Time Series Forecasting with TensorFlow](https://www.kaggle.com/code/nicholasjhana/univariate-time-series-forecasting-with-keras/notebook)
12. [Multi-Variate Time Series Forecasting with TensorFlow](https://www.kaggle.com/code/nicholasjhana/multi-variate-time-series-forecasting-tensorflow/notebook)
13. [Reducing Overfitting](https://www.kdnuggets.com/2019/12/5-techniques-prevent-overfitting-neural-networks.html)
14. [Data Augmentation](https://www.tensorflow.org/tutorials/images/data_augmentation)
15. [Layer Regularizers](https://johnthas.medium.com/regularization-in-tensorflow-using-keras-api-48aba746ae21)

## Guide to TensorFlow & Modeling

TensorFlow and Modeling has aaaaalotttt of information, but there are certain key things that are extremely useful to keep in mind. This section will go over the information that is absolutely crucial in creating good models with TensorFlow.

### 1. TensorFlow Inputs & Outputs Table

When building models, there are certain things to remember depending on the specific problem being modeled. The following tables summarize the input/output and model configurations for each type of the various problems being solved [4].

#### Inputs

Input shapes depend on the type of problem and network architecture. Input shape can be defined in the first layer of the network either calling the `input_shape` parameter or using the `tf.keras.layers.Input` class.

| Data Type      | Input Shape                                      |
| :--------------| :------------------------------------------------|
| Image          | (image height, image width, number of channels)  |
| Sequence       | (number of sequence steps, number of features)   |
| Structured     | (samples/batch size, features)                   |

#### Outputs
 
| Problem Type	        | Output Neurons        | Target Format   |	Loss Type	                               | Last Neuron Activation |
| :---------------------| :-------------------- | :-------------- | :----------------------------------------- | :--------------------- |
| Binary Classification	| 1	                    | Binary	      | binary_crossentropy                        | sigmoid                |
| Multi Classification	| Number of classes  	| One-Hot Encoded | categorical_crossentropy                   | softmax                |
| Multi Classification	| Number of classes	    | Label Encoded	  | sparse_categorical_crossentropy	           | softmax                |
| Regression	        | Number of predictions	| Numeric	      | Any regression metric: MSE/RMSE/MSLE/Huber | None                   |

### 2. Overfitting

Overfitting occurs when the model's predictions become highly variant. That is we see large variations between predictions in an effort to fit closer to the training set. The opposite can also occur, underfitting where the predictions do not generalize effectively.

There are a few methods to recognize if the model overfit the training data.

* Training loss declines while validation loss is constant or rises.
* A large gap between the training accuracy/ROC AUC/etc and the validation.
* Validation score does not change while validation loss declines.

## TensorFlow Certificate Candidate Handbook

The TensorFlow certificate exam provides a handbook that gives details on what to know for the exam. This section goes over each section of the Handbook, providing sample information regarding each question.

* [TensorFlow Certificate Candidate Handbook](https://www.tensorflow.org/static/extras/cert/TF_Certificate_Candidate_Handbook.pdf)

### Imports

In [119]:
import datetime
import os

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
import tensorflow_hub as hub

### Notebook Details

In [2]:
print(f'Notebook last run (end-to-end): {datetime.datetime.now()}')

Notebook last run (end-to-end): 2023-10-01 20:09:59.203369


### 1. TensorFlow Development Skills
You need to demonstrate that you understand how to develop software programs using TensorFlow and that you can find the information you need to work as an ML practitioner.

#### 1.1. Know how to program in Python, resolve Python issues, and compile and run Python programs in PyCharm.
* [Downloading PyCharm](https://www.jetbrains.com/pycharm/)
* [Learn PyCharm](https://www.jetbrains.com/pycharm/learn/)

#### 1.2. Know how to find information about TensorFlow APIs, including how to find guides and API references on tensorflow.org.
* [API Documentation](https://www.tensorflow.org/api_docs/python/tf)

#### 1.3. Know how to debug, investigate, and solve error messages from the TensorFlow API.
* [Debugging Tips](https://towardsdatascience.com/debugging-in-tensorflow-392b193d0b8)
* [TensorFlow Errors](https://www.tensorflow.org/api_docs/python/tf/errors)

#### 1.4. Know how to search beyond tensorflow.org, as and when necessary, to solve your TensorFlow questions.

#### 1.5. Know how to create ML models using TensorFlow where the model size is reasonable for the problem being solved.

* Sequential Model
* Functional API Model

##### Sequential Model

* `tf.keras.models.Sequential`
* https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

In [3]:
sequential_model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(2,), name='input_layer'),
    tf.keras.layers.Dense(10, activation='relu', name='hidden_layer_1'),
    tf.keras.layers.Dense(1, activation=tf.keras.activations.sigmoid, name='output'),
], name='sequential_model')

##### Functional API

* `tf.keras.models.Model`
* https://www.tensorflow.org/api_docs/python/tf/keras/Model

In [4]:
inputs = tf.keras.layers.Input(shape=(2,), name='input_layer')
x = tf.keras.layers.Dense(10, activation='relu', name='hidden_layer_1')(inputs)
outputs = tf.keras.layers.Dense(1, activation=tf.keras.activations.sigmoid, name='output')(x)

functional_model = tf.keras.models.Model(inputs, outputs, name='functional_model')

#### 1.6. Know how to save ML models and check the model file size.

Models can be saved in one of two formats: `h5` or `TF`.

* [Saving and Loading Models Article](https://www.kdnuggets.com/2021/02/saving-loading-models-tensorflow.html)

##### Saving Models

In [5]:
sequential_model.save('./models/sequential_model')

INFO:tensorflow:Assets written to: ./models/sequential_model/assets


INFO:tensorflow:Assets written to: ./models/sequential_model/assets


In [6]:
functional_model.save('./models/functional_model', save_format='h5')

/Users/brandonkubick/Code/deep-learning-development/env/lib/python3.9/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


##### Loading Models

In [10]:
sequential_model_loaded = tf.keras.models.load_model('./models/sequential_model')

In [13]:
functional_model_loaded = tf.keras.models.load_model('./models/functional_model')

##### Checking File Size

**TODO** Come back to check this

In [23]:
total_size = 0
for dir, _, files in os.walk('./models/sequential_model'):
    total_size += sum([os.path.getsize(f'{dir}/{file}') for file in files])

total_size

50965

In [16]:
os.path.getsize('./models/functional_model')

16016

#### 1.7. Understand the compatibility discrepancies between different versions of TensorFlow.

* https://www.tensorflow.org/guide/migrate/tf1_vs_tf2

### 2. Building and training neural network models using TensorFlow 2.x

You need to understand the foundational principles of machine learning (ML) and deep learning (DL) using TensorFlow 2.x.

#### 2.1. Use TensorFlow 2.x.

* https://blog.tensorflow.org/2019/09/tensorflow-20-is-now-available.html

In [7]:
tf.__version__

'2.13.0'

#### 2.2. Build, compile and train machine learning (ML) models using TensorFlow.

**Building Models**
* `tf.keras.models.Sequential`: Simple way of creating models with a single input, and are sequentially setup layers.
* `tf.keras.models.Model`: More customizable way of creating models, allowing multiple inputs, parallel/wide networks, and deep networks.

**Compiling Models**
* `model.compile`: Used to set how the model should learn through setting the optimizer and loss function.

**Training Models**
* `model.fit`: Used to actually train the models through passing in all the training specific information (data, epochs, validation data, batch size, etc.).

In [17]:
# Build Model (Sequential API)
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(5),
])

# Build Model (Functional API)
inputs = tf.keras.layers.Input(shape=(1,))
outputs = tf.keras.layers.Dense(5)(inputs)
model = tf.keras.models.Model(inputs, outputs)

In [18]:
# Compile Model
model.compile(loss='mae',
              optimizer=tf.keras.optimizers.legacy.Adam(),
              metrics=['mae', 'mse'])

In [19]:
# Train Model
history = model.fit(
    x=[1],
    y=[[1,2, 3, 4, 5]],
    epochs=1,
    callbacks=[],
    verbose=0)

#### 2.3. Preprocess data to get it ready for use in a model.

* Categorical Data needs to be converted to a numerical representation
    - Encode data using `sklearn.preprocessing.LabelEncoder`
    - One-hot Encode data using `sklearn.preprocessing.OneHotEncoder` or `tf.one_hot`
* Preprocessing Layers
    - [Preprocessing Layers](https://www.tensorflow.org/guide/keras/preprocessing_layers)

#### 2.4. Use models to predict results.

* `model.predict`: Used to predict the results given the corresponding inputs.

**NOTE**: the prediction outputs the probabilities in classification models, or the value in regression models. This is problematic for classification models, because classification means that is should be one value of a set of options rather than a probability.

* `tf.argmax`: Grabs the index of the maximum value (used to grab the corresponding classification class).
* `tf.round`: Rounds the probabilities. This doesn't always work for multi-class classification because all the probs can round to 0 if there are many classifications it can fall into.

In [22]:
tf.argmax([0.1, 0.2, 0.6, 0.12, 0.14])  # Highest index is 2

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [23]:
tf.round([0.1, 0.51, 0.3, 0.6, 0.12, 0.14])

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 1., 0., 1., 0., 0.], dtype=float32)>

#### 2.5. Build sequential models with multiple layers.

* `tf.keras.models.Sequential`

In [24]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,), name='Input'),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(1, name='Output'),
], name='SequentialModel')

#### 2.6. Build and train models for binary classification.

Binary classification is when the output is either 1 or 0 (only two choices).

* Ouput Shape = `(1,)`
* Output Activation Function = `sigmoid`
* Loss Function = `binary_crossentropy`

In [26]:
# Binary Model
binary_classification_model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(3,)),
    tf.keras.layers.Dense(1, activation='sigmoid'),
], name='binary_classification')

# Binary Model Compiling
binary_classification_model.compile(loss='binary_crossentropy',
                                    optimizer=tf.keras.optimizers.legacy.Adam())

#### 2.7. Build and train models for multi-class categorization.

Multi-class categorization is when the output is more than two options. This requires converting each category into a numerical representation.

* Output Shape = `(num_classes,)`
* Output Activation Function = `softmax`
* Loss Function = `categorical_crossentropy` if one-hot encoded format; `spare_categorical_crossentropy` if label encoded format

In [97]:
labels = tf.constant(['dog', 'cat', 'bird', 'dog'])
total_categories = 3  # dog, cat, bird

In [89]:
# Encoding Labels (With sklearn)
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

encoded_labels

array([2, 1, 0, 2])

In [98]:
# One-Hot-Encoding Labels (With TensorFlow)
one_hot_encoded_labels_tf = tf.one_hot(encoded_labels, total_categories)

# One-Hot-Encoding Labels (With sklearn)
one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded_labels_sklearn = one_hot_encoder.fit_transform(encoded_labels.reshape(-1, 1))

one_hot_encoded_labels_tf, one_hot_encoded_labels_sklearn

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]], dtype=float32)>,
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))

In [100]:
# Multi-class Model
multiclass_classification_model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(total_categories, activation='sigmoid'),
], name='binary_classification')

# Multi-class Model Compiling

# Using with one_hot_encoded_labels_tf when fitting
multiclass_classification_model.compile(loss='categorical_crossentropy',
                                        optimizer=tf.keras.optimizers.legacy.Adam())

# Using with encoded_labels when fitting
multiclass_classification_model.compile(loss='sparse_categorical_crossentropy',
                                        optimizer=tf.keras.optimizers.legacy.Adam())

#### 2.8. Plot loss and accuracy of a trained model.

When fitting a model, a history object is returned with the designated metrics the model was compiled with, along with the loss. This can be plotted using matplotlib.

* [History Object](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/History): The History object is associated as a callback that is automatically applied to the model when fitting and is returned by the fit method.

Some things to consider for the loss curves include:
* Ideally, the loss curve vor the validation loss and training loss will follow each other
* Point where training loss continues to decrease, but validation loss starts to stabilize implies `overfitting` (see section 2.9 below).

**NOTE** I have a personal toolbox, [py-learning-toolbox](https://github.com/bkubick/py-learning-toolbox), that will plot the histroy curve using the function, `ml_toolbox.analysis.history.plot_history`, and the designated metric desired to plot.

![image](screenshots/loss_curve.png)

#### 2.9. Identify strategies to prevent overfitting, including augmentation and dropout.

Overfitting occurs when the model learns the training data too well, that it can't predict test data or validation well. There are a handful of things that can be done to mitigate/prevent overfitting [Prevent Overfitting](https://www.kdnuggets.com/2019/12/5-techniques-prevent-overfitting-neural-networks.html).

* **Decrease complexity of model**: Not much to this, and not much to do to determine best route of simplifying model. Ultimately, just want to reduce the number of trainable parameters in the model.
* **Early Stopping**: A callback that can be implemented to stop the model from training once the validation loss is no longer decreasing.
* **More Data**: An obvious thing to do is add more data, but this isn't always possible.
* **Data Augmentation**: Transforming data to expand the dataset, and give a model various ways of viewing data. Specifically for image classification, popular data augmentation techniques include flipping image, rotating image, zoom image, etc.
* **Regularization**: A technique used to reduce complexity of a model through adding penalty terms to the loss function. This is done by adding regularizers to the corresponding layer through `kernel_regularizer`, `bias_regularizer`, or `activity_regularizer` kwarg.
  
    | L1 Regularization                                | L2 Regularization                         |
    | :-----------------                               | :----------------                         |
    | Penalizes sum of absolute values of weights      | Penalizes sum of square values of weights |
    | Generates model that is simple and interpretable | Able to learn complex data patterns       |
    | Robust to outliers                               | Not robust to outliers                    |

* **Dropout**: A technique that deactivates random neurons in the model while training, forcing each neuron to "learn", in theory, making each neuron more robust.

In [113]:
# Early Stopping Callback
# `patience`: how many epochs without improvement before ending training
# `start_from_epoch`: which epoch to start looking at stopping
early_stopping_callback = tf.keras.callbacks.EarlyStopping(patience=10, start_from_epoch=10)

In [117]:
# Data Augmentation ImageDataGenerator (Not Preferred)
data_augmented_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    rotation_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

# Data Augmentation (Preferred Method)
data_augmentation_model = tf.keras.models.Sequential([
    tf.keras.layers.RandomFlip('horizontal'),
    tf.keras.layers.RandomRotation(0.2),
    tf.keras.layers.RandomZoom(0.2),
    tf.keras.layers.RandomHeight(0.2),
    tf.keras.layers.RandomWidth(0.2),
    tf.keras.layers.Rescaling(1./255),
], name='DataAugmentation')

In [107]:
# Regularization
regularization_model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(5,
                          kernel_regularizer=tf.keras.regularizers.l1(0.01),
                          bias_regularizer=tf.keras.regularizers.l2(0.01),
                          activity_regularizer=tf.keras.regularizers.l1_l2(0.01, 0.01)),
    tf.keras.layers.Dense(1),
])

In [110]:
# Dropout
dropout_model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(1),
])

#### 2.10. Use pretrained models (transfer learning).

Transfer learning can be done by utilizing state of the art architectures trained on signifcant data through various studies, allowing for powerful models without the need for extreme training.

TensorFlow Hub provides various models that can be used for transfer learning.
* https://www.tensorflow.org/hub

In [120]:
transfer_model = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")

#### 2.11. Extract features from pre-trained models.
Feature extraction in transfer learning is when you take the underlying patterns (also called weights) a pretrained model has learned and adjust its outputs to be more suited to your problem. [[D. Bourke, Zero to Mastery](https://dev.mrdbourke.com/tensorflow-deep-learning/04_transfer_learning_in_tensorflow_part_1_feature_extraction/)]

In short, use transfer learning as a non-trainable base model, then pass the output of that to one or multiple layers dedicated to a specific problem (i.e. image classification by taking a model that knows 1000 foods, and add output layer to limit it to a set of only 10 foods).

In [126]:
base_model = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
base_model.trainable = False

inputs = tf.keras.layers.Input(shape=(), dtype=tf.string)
x = base_model(inputs)
outputs = tf.keras.layers.Dense(5)(x)  # Feature Extraction Used to dictate the outputs

model = tf.keras.models.Model(inputs, outputs)

#### 2.12. Ensure that inputs to a model are in the correct shape.

Inputs to a model are the specific parameters associated with the problem that are used to predict the output. In TensorFlow, the `shape` keyword to each layer automatically applies batching to the data ahead of time, meaning all that has to be specified is the shape of the inputs.

| Data Type      | Input Shape                                      |
| :--------------| :------------------------------------------------|
| Image          | (image height, image width, number of channels)  |
| Text           | (1,) - the string of the text                    |
| Sequence       | (number of sequence steps, number of features)   |
| Feed Forward   | (features)                   |

In [129]:
image_input = tf.keras.layers.Input(shape=(224, 224, 3))
text_input = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
sequence_input = tf.keras.layers.Input(shape=(7,))  # Window size of 7, 0 additional features
feed_forward = tf.keras.layers.Input(shape=(2,))  # two features used to predict

image_input.shape, text_input.shape, sequence_input.shape, feed_forward.shape  # The None is held for the batch size

(TensorShape([None, 224, 224, 3]),
 TensorShape([None, 1]),
 TensorShape([None, 7]),
 TensorShape([None, 2]))

#### 2.13. Ensure that you can match test data to the input shape of a neural network.

#### 2.14. Ensure you can match output data of a neural network to specified input shape for test data.

#### 2.15. Understand batch loading of data.

Batching is the process of using multiple samples of data at a time while training, to provide memory efficiency, faster training, and improved generalization. This is done in one of two ways in TensorFlow, while fitting, or through the dataset itself.

**NOTE** batch sizes in multiples of 8 typically work better with GPU's

In [133]:
# Fitting with batches
# Build Model (Sequential API)
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(5),
])

# Compile Model
model.compile(loss='mae', optimizer=tf.keras.optimizers.legacy.Adam())

# Train Model
model.fit(
    x=[1],
    y=[[1,2, 3, 4, 5]],
    epochs=1,
    batch_size=1,  # Batch Size
    verbose=0)

In [137]:
# Batching with dataset
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 1, 33, 5, 3])
batched_dataset = dataset.batch(3)
batched_dataset

<_BatchDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int32, name=None)>

#### 2.16. Use callbacks to trigger the end of training cycles.

Callbacks are used when training a model, and are ran at the end of each epoch. They can be used for saving, logging, adjusting learning rates, ending training, etc.

* https://www.tensorflow.org/api_docs/python/tf/keras/callbacks

In [139]:
# Used to stop training once model stops improving
early_stopping = tf.keras.callbacks.EarlyStopping()

# Used to store the model at the end of each epoch as a checkpoint.
# This is useful when needing to stop training early and pickup where you left off.
# Also useful to save the best trained model
checkpoint = tf.keras.callbacks.ModelCheckpoint('./checkpoints')

# Logs the metrics for each epoch to the corresponding CSV.
csv_logger = tf.keras.callbacks.CSVLogger('./logs/history.csv')

# Reduces the learning rate by a factor when the learning stops (hits a plateau)
lr_reducer = tf.keras.callbacks.ReduceLROnPlateau()

# LR Scheduler is used to update the learning rate for each epoch
# This is useful when triying to determine the optimal learning rate
lr_scheduler = tf.keras.callbacks.LearningRateScheduler(lambda epoch, lr: lr * 10 ** 2)

# Custom callback
lambda_callback = tf.keras.callbacks.LambdaCallback(on_batch_begin=lambda batch,logs: print(batch))

#### 2.17. Use datasets from different sources.

#### 2.18. Use datasets in different formats, including json and csv.

#### 2.19. Use datasets from tf.data.datasets.

* https://www.tensorflow.org/datasets/performances

### 3. Image classification

You need to understand how to build image recognition and object detection models with deep neural networks and convolutional neural networks using TensorFlow 2.x.

#### 3.1. Define Convolutional neural networks with Conv2D and pooling layers.

#### 3.3. Understand how to use convolutions to improve your neural network.

#### 3.4. Use real-world images in different shapes and sizes.

#### 3.5. Use image augmentation to prevent overfitting.

#### 3.6. Use ImageDataGenerator.

#### 3.7. Understand how ImageDataGenerator labels images based on the directory structure.

### 4. Natural language processing (NLP)

You need to understand how to use neural networks to solve natural language processing problems using TensorFlow.

#### 4.1. Build natural language processing systems using TensorFlow.

#### 4.2. Prepare text to use in TensorFlow models.

#### 4.3. Build models that identify the category of a piece of text using binary categorization

#### 4.4. Build models that identify the category of a piece of text using multi-class categorization

#### 4.5. Use word embeddings in your TensorFlow model.

#### 4.6. Use LSTMs in your model to classify text for either binary or multi-class categorization.

#### 4.7. Add RNN and GRU layers to your model.

#### 4.8. Use RNNS, LSTMs, GRUs and CNNs in models that work with text.

#### 4.9. Train LSTMs on existing text to generate text (such as songs and poetry)

### 5. Time series, sequences and predictions

You need to understand how to solve time series and forecasting problems in TensorFlow.

#### 5.1. Train, tune and use time series, sequence and prediction models.

#### 5.2. Train models to predict values for both univariate and multivariate time series.

#### 5.3. Prepare data for time series learning.

#### 5.4. Understand Mean Absolute Error (MAE) and how it can be used to evaluate accuracy of sequence models.

MAE is calculated by taking the absolute difference between the predicted and actual values ​​and averaging them. [10]

* **Advantages** MAE is simple and easy to interpret as the mean error is expressed in the same units as the original data. It is less sensitive to outliers compared to other error metrics such as mean squared error (MSE).
* **Disadvantages** MAE does not distinguish between overestimation and underestimation and does not provide information about the direction or magnitude of individual errors. In addition, depending on your particular problem it may be seen as a disadvantage that it does not penalize wrong predictions as much as MSE.

In [6]:
tf.metrics.mae([1, 2, 3, 4], [2, 3, 4, 5])

<tf.Tensor: shape=(), dtype=int32, numpy=1>

#### 5.5. Use RNNs and CNNs for time series, sequence and forecasting models.

* [LSTM](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM): Long Short Term Memory RNN [8]
* [GRU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU): Gated Recurrent Unit RNN. The purpose of this architecture is to solve the vanishing gradient problem. [9]
* [Bidirectional](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional): Layer that process the sequence input in both directions using the corresponding RNN layer as a parameter (LSTM, GRU, etc.). [7]

In [5]:
# Simple LSTM Layer
single_rnn_layer = tf.keras.layers.LSTM(12)
stacked_rnn_layer = tf.keras.layers.LSTM(12, return_sequences=True)

gru_layer = tf.keras.layers.GRU(12)

bidirectional_lstm_layer = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(12))
stacked_bidirectional_lstm_layer = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(12, return_sequences=True))

#### 5.6. Identify when to use trailing versus centered windows.

#### 5.7. Use TensorFlow for forecasting.

#### 5.8. Prepare features and labels.

#### 5.9. Identify and compensate for sequence bias.

#### 5.10. Adjust the learning rate dynamically in time series, sequence and prediction models.